gleanwork/mcp-server

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Adds issue, pull request, and feature templates for GitHub.
* Added new issue and pull request templates for GitHub to improve the contribution process, including detailed sections for bug reports, feature requests, and pull requests.
> internal: Adding issue, pull request, and feature templates for GitHub

- package.json
- pnpm-lock.yaml
- src/common/client.ts
- src/test/common/client.test.ts
- src/test/common/errors.test.ts
- src/test/mocks/handlers.ts
- src/test/mocks/setup.ts
- src/test/tools/chat.test.ts
- src/test/tools/search.test.ts
Handles token error cases, which are returned as `text/plain` but were getting parsed as JSON, resulting in an error.
Rather than rely on mocks, which can become outdated and drift from the actual solution under test, we've opted to move to using MSW to mock the actual API server. This means that our code is less reliant on a manufactured setup (with mocks replicating the API behavior). 
* Added improved error handling for token-based authentication failures, differentiating between expired and invalid tokens, while updating the response parsing logic to accommodate `text/plain` error responses.
This ensures more precise error messaging and user feedback during authentication failures.
- [] I have updated the documentation accordingly
> Provides better handling of invalid tokens. Also improves test infra.

- README.md
* The README.md has been updated to remove specific instructions on installation with package managers (npm, pnpm, yarn) and to clarify the API tokens' requirements and setup instructions. Additionally, sections for "Tools," "Debugging," and "Configuration" have been refined and formatted for better clarity.
* [Authentication - Glean Developer Portal](https://developers.glean.com/client/authentication): Details on authentication methods and requirements for API tokens.
* [Permissions - Glean Developer Portal](https://developers.glean.com/indexing/authentication/permissions): Information on permission types associated with API tokens. 
* [MCP Inspector](https://github.com/modelcontextprotocol/inspector): A developer tool for testing and debugging MCP servers.
> docs: Reworks README.md to include more specific detail around the API tokens

- .prettierrc
- .vscode/launch.json
- README.md
- package.json
- pnpm-lock.yaml
- src/common/version.ts
- src/configure.ts
- src/configure/client/claude.ts
- src/configure/client/cursor.ts
- src/configure/client/windsurf.ts
- src/configure/index.ts
- src/index.ts
- src/server.ts
- src/test/cli.test.ts
- src/test/common/errors.test.ts
- src/test/validate-flags.test.ts
Adds `configure` command to ease the installation of the MCP server locally.
Users can now do:
```bash
npx @gleanwork/mcp-server configure --client cursor --token your_api_token --domain your_subdomain
```
* Added new client configurations for Claude Desktop, Cursor, and Windsurf, including their respective configuration paths, templates, and success messages. (`src/client/claude.ts` [[1]](diffhunk://#diff-be61ee2e3402f704a265783f4866522a3cbd860d61cf53bc422cef34e5380129R1-R71) `src/client/cursor.ts` [[2]](diffhunk://#diff-e71eba3bf8a795a4cf9d895987f68fb1af88d3c8672cffe05c7bbc1b70849cfeR1-R61) `src/client/windsurf.ts` [[3]](diffhunk://#diff-e159788d2e7e6dd7ffe2c1d96a0cb96341dd2d72a6062cb4c59698e63b09741eR1-R62)
* Introduced a common interface and types for MCP client implementations and …
> feat: Adds the ability to run an configure command to configure the MCP Server

- src/test/cli.test.ts
Add version number normalization to prevent test failures when version changes (currently breaking CI).
#45 
#46 
#43 
&c
> chore(test): normalize version output in CLI tests

- src/test/cli.test.ts
A single test to validate that we're printing user-friendly error messages and not dumping stack traces to the user.
Fast follow to #48 .
Fixes #
just tests
> test: Add bin-tester for OAuth

- src/auth/auth.ts
- src/auth/error.ts
- src/test/auth/authorize.test.ts
- src/test/cli.test.ts
> feat(auth): error gracefully in non-interactive TTY

- .cursor/rules/node-testing.mdc
> feat(ai): Add cursor testing rules

- .cursor/rules/node-testing.mdc
- .cursor/rules/typescript-style-guide.mdc
1. Re-arrange testing rules and encourage inline snapshots for error
matching.
2. Add a barebones ts style guide rule that we can add more to later.
Fixes #
> chore: tweak cursor rules

- src/auth/auth.ts
- src/configure.ts
- src/configure/index.ts
- src/index.ts
- src/test/cli.test.ts
- src/test/validate-flags.test.ts
When the user runs `--configure` (i.e. installs the tool), run the auth flow to acquire an access token.
Fixes #
> feat(auth): Trigger auth flow on install

- src/index.ts
Add errors in the log file when running `auth-test`.
Fixes #
> chore(logging): auth-test errors

- src/auth/auth.ts
Add some docs explaining why `getOAuthScopes` even needs to exist.
Fixes #
> chore: Add comments

- .cursor/rules/typescript-style-guide.mdc
tell cursor we use pnpm
Fixes #
> chore: cursor rules

- src/configure.ts
- src/index.ts
- src/test/cli.test.ts
- src/test/validate-flags.test.ts
Gating OAuth functionality until it's ready for production.
> task: Gate OAuth behind an env var

- CODEOWNERS
> task: Adding CODEOWNERS

- .github/ISSUE_TEMPLATE/bug_report.md
Fixes issue template to use new `GLEAN_INSTANCE` env var.
> internal: Fixes issue template

- README.md
- src/configure.ts
- src/server.ts
- src/test/mocks/handlers.ts
- src/test/server.test.ts
- src/test/tools/people_profile_search.test.ts
- src/tools/chat.ts
- src/tools/people_profile_search.ts
- src/tools/search.ts
Adds People profile search tool. Additionally adds more useful server tests to validate integration.
* Adds a new "People Profile Search" tool to facilitate searching through the company’s people directory, along with necessary modifications to the server and test files for integration and validation. 
This change enriches the functionality provided by the Glean MCP Server, integrating enhanced search capabilities specifically for employee information.
> feat: Adds people search tool

- src/index.ts
Use the new tool format for auth-test.  It makes the logs much easier to read to validate the details of the auth test.
Update the test to ask chat "Who am I?".
Fixes #
> feat(auth-test): readability

- src/configure.ts
- src/test/cli.test.ts
- src/test/mocks/handlers.ts
- src/test/util/preflight.test.ts
- src/util/preflight.ts
Add capability to validate instance names before proceeding with operations. The validation makes a request to the running instance's liveness check endpoint to verify that the instance exists and is accessible.
> feat(configure): add `--instance` preflight validation for configure

- src/configure.ts
This pull request updates the error messaging in the `configure` function to provide clearer guidance for troubleshooting connection issues with a Glean instance.
* [`src/configure.ts`](diffhunk://#diff-5e04f9154aa4746216a242b0d59346f84204e10d27ca9d386c6d3bc198b8abdcL126-R138): Enhanced the error message when validating a Glean instance fails. The new message includes specific troubleshooting tips, such as verifying the instance name, checking the internet connection, and referencing the Glean admin page for the server instance.
> fix: Making preflight validation message more clear

- .vscode/launch.json
> chore: Add launch config

- src/configure.ts
- src/configure/client/vscode.ts
- src/configure/index.ts
- src/index.ts
- src/test/cli.test.ts
- src/test/configure/vscode.test.ts
This pull request introduces support for creating both global and local workspace configurations for the VS Code client in the Glean MCP tool. It includes updates to the configuration logic, new types for configuration formats, and enhancements to the VS Code-specific client implementation.
* Added support for a `--local` flag to create local workspace configurations for VS Code, including validation to ensure the flag is used in a valid workspace directory. (`src/configure.ts`, `src/configure/client/vscode.ts`, `src/index.ts`) [[1]](diffhunk://#diff-5e04f9154aa4746216a242b0d59346f84204e10d27ca9d386c6d3bc198b8abdcR125-R144) [[2]](diffhunk://#diff-ae2e390ff04b0b2196520b9c801f8258a5e683a7755fb5d67b46963fa1bf9c91L52-L74) [[3]](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707a …
> feat: Implements local configuration for vscode (to complement the global one)

- .vscode/launch.json
- src/configure.ts
- src/index.ts
- src/test/cli.test.ts
- src/test/validate-flags.test.ts
This pull request introduces several updates to improve the configuration and validation processes for Glean client credentials, enhance debugging capabilities, and expand test coverage. Key changes include refining credential handling logic, updating debugging configurations, and adding new test cases to ensure robust validation.
* Refactored `configure` function in `src/configure.ts` to load credentials from multiple sources (flags, environment variables, `.env` files) and prioritize them appropriately. Improved error messages for missing credentials. [[1]](diffhunk://#diff-5e04f9154aa4746216a242b0d59346f84204e10d27ca9d386c6d3bc198b8abdcL168-R173) [[2]](diffhunk://#diff-5e04f9154aa4746216a242b0d59346f84204e10d27ca9d386c6d3bc198b8abdcL181-R191)
* Updated `validateFlags` in `src/index.ts` …
> fix(cli): Fixes .env file and process.env support in configure

- packages/configure-mcp-server/src/common/env.ts
- packages/configure-mcp-server/src/configure/index.ts
- packages/configure-mcp-server/src/test/cli.test.ts
- packages/configure-mcp-server/src/test/configure.test.ts
There's still a disable env var but that exists to run the CLI tests.
> Enable OAuth by default (without environment variable)

- package.json
- pnpm-lock.yaml
Update @release-it-plugins/workspaces to include https://github.com/release-it-plugins/workspaces/pull/127.
> chore(release): Fix publishing

- package.json
- pnpm-lock.yaml
Fix from https://github.com/release-it-plugins/workspaces/pull/128
> chore(release): Ensure releaser has ran `pnpm login`
