- CHANGELOG.md
- RELEASE.md
- package.json
- pnpm-lock.yaml
Adds `release-it` to facilitate NPM releases.
To release, you'll need to ensure you've [generated a GitHub PAT](https://github.com/settings/tokens/new?scopes=repo&description=GITHUB_AUTH+env+variable), and made it available via the `GITHUB_AUTH` environment variable.
Then, you can use the following:
```sh
pnpm release-it
```
...and follow the prompts.
> internal: Adds release-it for package releases

- package.json
In order to publish a scoped package, you need to set the `package.json`'s `publishConfig.access` to "public". In addition, this change adds a bin script to the repository, which allows for correct invocation of the MCP server via an MCP client (MCP clients use `npx -y <packageName>` to invoke the server, and that requires a package bin to work correctly.
> fix: Fixes scoped package publishing. Adds bin script

- package.json
Fixes publish paths in the `files` section of the package.json. This ensures we're publishing the correct package contents to NPM.
> fix: Fixes file paths in package.json to ensure we're publishing the correct contents

- src/tools/search.ts
Without a default `pageSize` parameters that's non-zero, the `/search` endpoint will return 0 results. This change applies a default pageSize of 10. This value was deemed a good compromise to give enough results without being overly verbose.
The reason adding it to the zod schemas works is because we're using `schema.parse` to validate the inbound params, and zod will "fill in" missing defaults during parse.
> fix: Adds defaults for search.pageSize (otherwise no results are returned)

- package.json
- src/test/tools/schemas.test.ts
- src/tools/chat.ts
- src/tools/schemas.ts
- src/tools/search.ts
Updates Zod schemas to use full type definitions.
A number of the Zod schemas defined initially were underspecified, meaning that they at times defined a schema property as an `Any` type. This resulted in an underspecified JSON schema when converting the Zod schemas to the required `inputSchema` that the MCP tool requires. Using this underspecified schema in the MCP tool in combination with the OpenAI Agent's SDK resulted in errors, specifically around the fact that the schema types weren't correctly or fully defined JSON schemas. This change addresses this by ensuring we have full schemas defined (using `openai-zod-client` to generate the schemas in full).
> Fix schema validation errors

- src/auth/auth.ts
- src/auth/error.ts
- src/test/auth/auth.test.ts
- src/test/cli.test.ts
AuthError now has codes that indicate the specific failure.  The codes are printed as part of the message to the user, e.g.
```
Authorization failed: ERR_A_06: Unable to fetch OAuth protected resource metadata: please contact your Glean administrator and ensure device flow authorization is configured correctly.
```
Fast follow to #48.
Fixes #
> feat: Add error codes

- src/auth/auth.ts
- src/auth/error.ts
- src/test/auth/authorize.test.ts
When polling for authorization grants, time out after 10 minutes.
10m is hardcoded but we can add a command-line flag later if need be.
Fixes #
> feat: Polling times out after 10m

- src/auth/auth.ts
- src/auth/error.ts
- src/auth/types.ts
- src/test/auth/auth.test.ts
RFC 8628§3.2 describes a device authorization response as containing `verification_uri` but some providers like `url` more than the spec.
Normalize the response to support both.
Fixes #
> feat(auth): Support verification_url

- src/auth/auth.ts
- src/test/auth/auth.test.ts
- src/test/auth/authorize.test.ts
We can get token and authorization endpoints from either openid-configuration or oauth-resource-metadata.  The former is newer and better supported.
Still keeping oauth-resource-metadata as a fallback.
Fixes #
> feat(auth): prefer openid-configuration

- src/auth/auth.ts
- src/test/auth/authorize.test.ts
Previously we would fail gracelessly in the case where the token poller rejected on the first very request, i.e. before we awaited the tokenPoller (and therefore had a reject handler attached).
Fixes #
> fix(auth): token poller

- package.json
- pnpm-lock.yaml
We require node >= 18 which ships fetch.
Fix #11
> chore: remove node-fetch dep

- src/server.ts
- src/test/tools/chat.test.ts
- src/test/tools/search.test.ts
- src/tools/chat.ts
- src/tools/search.ts
The current implementation uses the raw schemas from both the `/search` and `/chat` endpoints. These don't work well as MCP tools, since the schemas are vastly more complex than an LLM can understand, and it really struggles to formulate coherent requests.
This change introduces new simplified schemas instead. These schemas are more LLM friendly, and allow for a higher probability that the tool will be able to be understood and invoked. We take these new tool requests and map them to the API requests that are passed through to the client, and hence provide the clean mapping between tool request and API request.
Fixes #80 
Fixes #83
> task: Simplifies schemas to provide a more consistent tool invocation

- README.md
- src/auth/auth.ts
- src/common/client.ts
- src/config/config.ts
- src/configure.ts
- src/configure/index.ts
- src/index.ts
- src/test/cli.test.ts
- src/test/common/client.test.ts
- src/test/mocks/handlers.ts
- src/test/tools/chat.test.ts
- src/test/tools/search.test.ts
- src/test/validate-flags.test.ts
We're moving to standardize our language for the required parameters in our various public APIs. We're changing the term `domain` to `instance` as that better describes what that parameter represents (it's the customers' Glean instance).
This PR updates the language we're using in this repository, which still maintaining backwards compatibility for the old naming convention.
> task: Updates usages of domain/subdomain to instance

- .github/workflows/ci.yml
- package.json
Updated the CI configuration to support Node.js versions 20.x, 22.x, and added 24.x, while pinning the package engine minimum Node.js version to 20.
> chore: Bumping node, pinning to lowest version, updating ci matrix

- src/test/auth/auth.test.ts
Make sure XDG env vars are set for all the auth tests so we don't override the user's local tokens.
Fixes #
> fix(test): Run auth tests isolated

- src/index.ts
- src/test/cli.test.ts
Add `npx @gleanwork/mcp-server server` subcommand. There is no functional change here (if you invoke without a subcommand we do just as before -> run the server). 
Sets the stage for future refactorings allowing `--instance` and `--token` to be specified.
> feat(cli): add explicit 'server' command as default

- src/index.ts
- src/server.ts
- src/test/cli.test.ts
Add command line options to directly specify Glean instance and API token when running the server:
- Add `--instance` (`-i`) and `--token` (`-t`) options for server command
- Update documentation and help text to reflect new options
- Add example showing usage with new options
- Pass CLI arguments to runServer function to set environment variables
> feat(cli): add instance and token options to server command

- src/auth/auth.ts
- src/common/client.ts
- src/config/config.ts
- src/test/common/client.test.ts
- src/test/config/config.test.ts
Have `getConfig` itself take an option for auto-upgrading OAuth if it can only discover basic config.
This forces the function async, but all callers are already in async contexts.
> chore(dx): Improve getConfig ergonomics

- .github/dependabot.yml
This commit removes the deprecated `reviewers` field from dependabot.yml.  According to GitHub, this field will be removed soon and repository code  owners (CODEOWNERS file) should be used instead to specify reviewers for  Dependabot PRs.
See: https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
> chore(dependabot): remove deprecated reviewers field

- README.md
- src/configure.ts
- src/configure/client/vscode.ts
- src/configure/index.ts
- src/test/cli.test.ts
- src/test/configure/vscode.test.ts
Implement VS Code client integration for MCP configuration.
I also added `upateConfig` and `hasExistingConfig` methods to the base client interface. This allows us to defer the detection (i.e. if the server is already configured) and the actual updating logic (i.e. writing to the config file) to the underlying `MCPClientConfig` implementation. This is largely because VSCode's structure is pretty different from the others. In order to avoid annoying duplication, I've left the default implementation in the base client (shared by cursor, windsurf, claude), and then override that in the VSCode client.
Fixes #124
> feat(configure): add VS Code MCP client support

- packages/configure-mcp-server/package.json
- packages/local-mcp-server/package.json
- packages/mcp-server-utils/package.json
remove `--max-old-space-size=4096'` from test commands.  Tests still pass, we don't need to aggressively demand lots of memory.
Downstream of #146
> chore(testing): drop bigmem

- packages/configure-mcp-server/tsconfig.json
- packages/local-mcp-server/tsconfig.json
- packages/mcp-server-utils/tsconfig.json
These path aliases hurt rather than help.  They cause auto-completion imports to be wrong and rely on tsc-alias, but we don't use tsc-alias.
We can add the path imports back in if we care, and if we do we should add tsc-alias at the same time.
Downstream of #146
> dev(lsp): remove ts path aliases

- packages/mcp-server-utils/src/common/client.ts
The `SDK_METADATA` for `@gleanwork/api-client` looks like:
```js
{
language: 'typescript',
openapiDocVersion: '0.9.0',
sdkVersion: '0.6.1',
genVersion: '2.610.0',
userAgent: 'speakeasy-sdk/typescript 0.6.1 2.610.0 0.9.0 @gleanwork/api-client'
}
```
This PR introduces a custom `User-Agent` string specifically for `@gleanwork/local-mcp-server`. It is very similar to the default, but it customizes the version (second field) to be the published package version and the package name (last field) to be
`@gleanwork/local-mcp-server`. This will allow us to get a better understanding of usage volume.
> feat(local-mcp-server): add custom user-agent header

- packages/configure-mcp-server/package.json
- packages/local-mcp-server/package.json
- packages/mcp-server-utils/package.json
Without this change, `tsc` will happily build into `build/` again *but* it never clears deleted files. This means if you move a file, you are mega trolled.
Stacked on top of #154
> fix: Ensure `build/` is cleared before running `tsc`

- .vscode/launch.json
- packages/configure-mcp-server/src/common/env.ts
- packages/configure-mcp-server/src/configure/client/claude.ts
- packages/configure-mcp-server/src/configure/client/cursor.ts
- packages/configure-mcp-server/src/configure/client/index.ts
- packages/configure-mcp-server/src/configure/index.ts
- packages/configure-mcp-server/src/index.ts
- packages/configure-mcp-server/src/test/cli.test.ts
- packages/mcp-server-utils/package.json
- packages/mcp-server-utils/src/auth/auth.ts
- packages/mcp-server-utils/src/auth/error.ts
- packages/mcp-server-utils/src/auth/oauth-cache.ts
- packages/mcp-server-utils/src/auth/types.ts
- packages/mcp-server-utils/src/test/auth/auth.test.ts
- packages/mcp-server-utils/src/util/index.ts
- pnpm-lock.yaml
Updates configure to have two subcommands
- `npx @gleanwork/configure-mcp-server local`
- `npx @gleanwork/configure-mcp-server remote`
`local` is the default and configures the local mcp server.
`remote` sets up our fork of `mcp-remote` to connect to either the `agents` or `tools` MCP servers.
If OAuth is enabled via the environment variable `GLEAN_OAUTH_ENABLED`, after authentication the tokens and client information are copied to where `mcp-remote` will look for them.  The access token is given a very short expiration (1s) so that mcp-go will use its own acquired access tokens.  The important part is that it has the refresh token.
**Note**: This is a stop-gap until we can fully support the authorization spec on the server.
The DX for refresh token expiration is currently quite poor. …
> feat: configure remote mcp-server

- packages/mcp-server-utils/src/auth/token-store.ts
- packages/mcp-server-utils/src/test/auth/auth.test.ts
When a refresh response includes a refresh token, save that to tokens.json.  When a refresh response does not include a refresh token (as with gsuite), assume the existing refresh token is unexpired and keep it around.
Also clean up some unnecessary test mocking.
> fix(auth): keep unexpired refresh tokens

- package.json
- pnpm-lock.yaml
Updates to land the fix for ensuring that pnpm lockfile is updated before publishing (https://github.com/release-it-plugins/workspaces/pull/120).
> fix(release): Ensure `pnpm-lock.yaml` is updated on release

- packages/configure-mcp-server/src/configure/client/index.ts
- packages/configure-mcp-server/src/configure/client/vscode.ts
- packages/configure-mcp-server/src/configure/index.ts
- packages/configure-mcp-server/src/test/cli.test.ts
- packages/configure-mcp-server/src/test/configure.test.ts
- packages/configure-mcp-server/src/test/configure/vscode.test.ts
If there's an existing `glean` mcp config for the local server, update it to the remote server when running `remote`
rename local and agents servers so the set of server names is now
- `glean` (default)
- `glean_agents`
- `glean_local`
Also remove the check for not updating an existing config.  It's not worth the complexity now that we have three different configurations.
> feat: update config local -> remote

- packages/configure-mcp-server/src/configure/client/index.ts
- packages/configure-mcp-server/src/configure/client/vscode.ts
- packages/configure-mcp-server/src/test/cli.test.ts
Remove the last piece of the success message:
> Notes:
> - You may need to set your Glean instance and API token if they weren't provided during configuration
> - Configuration is at: ${configPath}
As it's not relevant for remote setup.  We can add it back later for local-only if we want, but we expect remote to be the go-forward path.
> feat: rework success message

- packages/local-mcp-server/README.md
- packages/local-mcp-server/src/server.ts
- packages/local-mcp-server/src/test/tools/read_documents.test.ts
- packages/local-mcp-server/src/tools/read_documents.ts
- packages/mcp-server-utils/package.json
Adds a `read_documents` tool to the local MCP server so that we can get full document contents 
There are plenty of examples where having the full document contents really helps, but here's a simple example:
When I drop a link and ask Glean MCP to analyze, it'll either do a search or a chat. Search is somewhat useful, but we're still snippeting there so we don't get the full picture of the document. We should be able to analyze the entirety of the document using the link.
Connecting local MCP through local server:
Seems to be an issue with the response from the client SDK, so filed an issue [here](https://github.com/gleanwork/api-client-typescript/issues/45) and replaced it with a fetch for now
> [tool] Add read_documents MCP tool for retrieving documents by ID or URL

- packages/local-mcp-server/package.json
- pnpm-lock.yaml
Document search fails when certain related documents come back.  This is because relation types like "contact" can come back lowercase even though the openapi spec has it uppercase.
This is fixed in 0.7 of the api client by including both values in the enum.
> fix: related docs

- packages/mcp-server-utils/src/auth/auth.ts
- packages/mcp-server-utils/src/test/auth/auth.test.ts
Request `offline_access` scope by default.  Several providers require this in order to issue refresh tokens, which we depend on.
> Fix Azure OAuth support

- packages/mcp-server-utils/package.json
- pnpm-lock.yaml
- Includes fix for CVE-2025-6514
> fix: bump mcp-remote fork to 0.2.2

- packages/configure-mcp-server/package.json
- packages/configure-mcp-server/src/test/cli.test.ts
- packages/configure-mcp-server/src/test/configure.test.ts
- packages/configure-mcp-server/src/test/configure/vscode.test.ts
- packages/mcp-server-utils/package.json
- pnpm-lock.yaml
Bump the mcp-remote fork to include the fix for proper openid configuration discovery.  This is necessary for OAuth authorization servers that:
1. Advertise openid-configuration but not oauth-authorization-server and
2. Have a path component in the URL.
This includes Azure.
> fix: Support Azure

- packages/configure-mcp-server/package.json
- packages/mcp-server-utils/src/auth/auth.ts
- packages/mcp-server-utils/src/config/index.ts
- packages/mcp-server-utils/src/test/auth/authorize.test.ts
- packages/mcp-server-utils/src/util/pkce.ts
- pnpm-lock.yaml
* Added PKCE support for OAuth device flow specifically for `onelogin.com`, including changes to the `GleanOAuthConfig` to incorporate `codeVerifier`, `codeChallenge`, and `codeChallengeMethod` fields. Implemented utility functions for generating PKCE pairs, alongside updates in the authentication logic to support these changes.
* New script added in the `package.json` for easier execution (`go` command using `tsx`). 
Fixes #
> Add support for onelogin device flow
